skip: True 
dataset: "../datasets/CICIDS-2017"
batch_size: 256
benign_file: "Monday-WorkingHours.pcap_ISCX"
fe_class: "AfterImageGraph"
fe_name: "AfterImageGraph(TCP,UDP,ARP,ICMP,Other)"
model_names:
- "ICL"
- "Kitsune"
- "AE"
- "VAE"
node_encoders:
- "LinearNodeEncoder"
- "GCNNodeEncoder"
- "GATNodeEncoder"
distribution:
- "log-normal"
- "uniform"
- "gaussian"